In [ ]:
#원주가, 수정 주가 둘 다 한번에 조회
import os
import requests
import pandas as pd


API_TOKEN = os.getenv('TIINGO_API_TOKEN')

ticker = "AAPL"
start_date = "2025-10-01"
end_date = "2026-10-10"

url = f"https://api.tiingo.com/tiingo/daily/{ticker}/prices"

params = {
    "startDate": start_date,
    "endDate": end_date,
    "token": API_TOKEN,
}

response = requests.get(url, params=params)
response.raise_for_status()

data = response.json()

df = pd.DataFrame(data)

df

,date,close,high,low,open,volume,adjClose,adjHigh,adjLow,adjOpen,adjVolume,divCash,splitFactor
0,2025-10-01T00:00:00.000Z,255.45,258.79,254.93,255.040,48713940,254.504435,257.832072,253.986360,254.095952,48713940,0.0,1.0
1,2025-10-02T00:00:00.000Z,257.13,258.18,254.15,256.575,42630239,256.178216,257.224330,253.209247,255.625271,42630239,0.0,1.0
2,2025-10-03T00:00:00.000Z,258.02,259.24,253.95,254.665,49155614,257.064922,258.280406,253.009987,253.722341,49155614,0.0,1.0
3,2025-10-06T00:00:00.000Z,256.69,259.07,255.05,257.990,44664118,255.739845,258.111035,254.105915,257.035033,44664118,0.0,1.0
4,2025-10-07T00:00:00.000Z,256.48,257.40,255.43,256.805,31955776,255.530622,256.447217,254.484509,255.854419,31955776,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,2026-10-05T00:00:00.000Z,332.89,336.21,331.65,332.815,34400850,332.890000,336.210000,331.650000,332.815000,34400850,0.0,1.0
254,2026-10-06T00:00:00.000Z,333.63,334.38,330.62,332.280,30449005,333.630000,334.380000,330.620000,332.280000,30449005,0.0,1.0
255,2026-10-07T00:00:00.000Z,336.67,338.67,332.78,336.960,34147860,336.670000,338.670000,332.780000,336.960000,34147860,0.0,1.0
256,2026-10-08T00:00:00.000Z,340.42,341.57,335.90,336.815,35332449,340.420000,341.570000,335.900000,336.815000,35332449,0.0,1.0
257,2026-10-09T00:00:00.000Z,336.64,338.61,330.70,331.695,37881199,336.640000,338.610000,330.700000,331.695000,37881199,0.0,1.0

In [ ]:
#원주가 조회
raw_df = df[
    [
        "date",
        "open",
        "high",
        "low",
        "close",
        "volume",
    ]
].copy()

raw_df["date"] = pd.to_datetime(raw_df["date"]).dt.date

for col in ["open", "high", "low", "close"]:
    raw_df[col] = pd.to_numeric(raw_df[col])

raw_df["volume"] = pd.to_numeric(raw_df["volume"])

raw_df

           date     open    high     low   close    volume
0    2025-10-01  255.040  258.79  254.93  255.45  48713940
1    2025-10-02  256.575  258.18  254.15  257.13  42630239
2    2025-10-03  254.665  259.24  253.95  258.02  49155614
3    2025-10-06  257.990  259.07  255.05  256.69  44664118
4    2025-10-07  256.805  257.40  255.43  256.48  31955776
..          ...      ...     ...     ...     ...       ...
253  2026-10-05  332.815  336.21  331.65  332.89  34400850
254  2026-10-06  332.280  334.38  330.62  333.63  30449005
255  2026-10-07  336.960  338.67  332.78  336.67  34147860
256  2026-10-08  336.815  341.57  335.90  340.42  35332449
257  2026-10-09  331.695  338.61  330.70  336.64  37881199

[258 rows x 6 columns]

In [ ]:
#수정주가
adj_df = df[
    [
        "date",
        "adjOpen",
        "adjHigh",
        "adjLow",
        "adjClose",
        "adjVolume",
    ]
].copy()

adj_df["date"] = pd.to_datetime(adj_df["date"]).dt.date

for col in ["adjOpen", "adjHigh", "adjLow", "adjClose"]:
    adj_df[col] = pd.to_numeric(adj_df[col])

adj_df["adjVolume"] = pd.to_numeric(adj_df["adjVolume"])

adj_df

           date     adjOpen     adjHigh      adjLow    adjClose  adjVolume
0    2025-10-01  254.095952  257.832072  253.986360  254.504435   48713940
1    2025-10-02  255.625271  257.224330  253.209247  256.178216   42630239
2    2025-10-03  253.722341  258.280406  253.009987  257.064922   49155614
3    2025-10-06  257.035033  258.111035  254.105915  255.739845   44664118
4    2025-10-07  255.854419  256.447217  254.484509  255.530622   31955776
..          ...         ...         ...         ...         ...        ...
253  2026-10-05  332.815000  336.210000  331.650000  332.890000   34400850
254  2026-10-06  332.280000  334.380000  330.620000  333.630000   30449005
255  2026-10-07  336.960000  338.670000  332.780000  336.670000   34147860
256  2026-10-08  336.815000  341.570000  335.900000  340.420000   35332449
257  2026-10-09  331.695000  338.610000  330.700000  336.640000   37881199

[258 rows x 6 columns]