ALPHA_VANTAGE_API 무료 플랜 제한 사항
- 일일 호출 제한 25회
- 최근 100 거래일의 데이터만 받을 수 있음



Tiingo라는 대체 API 존재 (D19.ipynb에서 코드 확인 가능)
- Tiingo 무료 플랜 사용 시 시간당 50회
- 일 1,000회 요청이 가능
- 월별 고유 심볼은 최대 500
- 월 1GB bandwidth 제한
- 1회 요청으로 원하는 기간의 데이터를 한번에 받을 수 있음
- 원주가와 수정주를 한번에 제공

In [13]:
import requests
import pandas as pd
import os

API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY")

SYMBOL = "AAPL"

ALPHAVANTAGE_URL = "https://www.alphavantage.co/query"

params = {
    "function": "TIME_SERIES_DAILY",
    "symbol": SYMBOL,
    "outputsize": "compact",   # 무료: 최근 100 거래일
    "apikey": API_KEY,
}

# "outputsize":"full"로 25년+ 전체 데이터를 받는 기능은 Premium

response = requests.get(ALPHAVANTAGE_URL, params=params)
print(response.url)

response.raise_for_status()

data = response.json()

data

https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=AAPL&outputsize=compact&apikey=OSNDPAM8M304CM80

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'AAPL',
  '3. Last Refreshed': '2026-10-12',
  '4. Output Size': 'Compact',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2026-10-12': {'1. open': '338.2150',
   '2. high': '342.6300',
   '3. low': '337.6000',
   '4. close': '340.9700',
   '5. volume': '25900599'},
  '2026-10-09': {'1. open': '331.6950',
   '2. high': '338.6100',
   '3. low': '330.7000',
   '4. close': '336.6400',
   '5. volume': '37881199'},
  '2026-10-08': {'1. open': '336.8150',
   '2. high': '341.5700',
   '3. low': '335.9000',
   '4. close': '340.4200',
   '5. volume': '35332449'},
  '2026-10-07': {'1. open': '336.9600',
   '2. high': '338.6700',
   '3. low': '332.7800',
   '4. close': '336.6700',
   '5. volume': '34147860'},
  '2026-10-06': {'1. open': '332.2800',
   '2. high': '334.3800',
   '3. low': '330.6200',
   '4. close': '333.6300',
   '5. volume': '30449005'},
  '2026-10-05': {'1. open': '332.8150',
   '2. high': '336.2100',
   '3. low': '331.6500',
   '4. close': '332.8900',
   '5. volume': '34400850'},
  '2026-10-02': {'1. open': '333.2600',
   '2. high': '334.5400',
   '3. low': '330.6100',
   '4. close': '333.6900',
   '5. volume': '33278552'},
  '2026-10-01': {'1. open': '330.0000',
   '2. high': '332.4816',
   '3. low': '325.8100',
   '4. close': '330.3200',
   '5. volume': '36306346'},
  '2026-09-30': {'1. open': '330.8000',
   '2. high': '339.5000',
   '3. low': '330.1401',
   '4. close': '333.0200',
   '5. volume': '49988558'},
  '2026-09-29': {'1. open': '336.9650',
   '2. high': '337.0850',
   '3. low': '328.7000',
   '4. close': '329.4000',
   '5. volume': '38478037'},
  '2026-09-28': {'1. open': '340.3700',
   '2. high': '342.9880',
   '3. low': '338.0400',
   '4. close': '338.4000',
   '5. volume': '32820848'},
  '2026-09-25': {'1. open': '336.0400',
   '2. high': '341.6700',
   '3. low': '334.5300',
   '4. close': '341.0700',
   '5. volume': '30002507'},
  '2026-09-24': {'1. open': '336.7200',
   '2. high': '338.9100',
   '3. low': '334.3000',
   '4. close': '335.9200',
   '5. volume': '24733098'},
  '2026-09-23': {'1. open': '341.0750',
   '2. high': '341.8000',
   '3. low': '335.5000',
   '4. close': '337.0200',
   '5. volume': '31658823'},
  '2026-09-22': {'1. open': '340.1350',
   '2. high': '345.3400',
   '3. low': '338.7500',
   '4. close': '339.7500',
   '5. volume': '40711786'},
  '2026-09-21': {'1. open': '335.2800',
   '2. high': '339.6400',
   '3. low': '333.0500',
   '4. close': '338.9800',
   '5. volume': '34999229'},
  '2026-09-18': {'1. open': '337.9050',
   '2. high': '338.4900',
   '3. low': '332.5300',
   '4. close': '336.1300',
   '5. volume': '86588203'},
  '2026-09-17': {'1. open': '334.7700',
   '2. high': '338.3400',
   '3. low': '330.1833',
   '4. close': '337.0000',
   '5. volume': '36700225'},
  '2026-09-16': {'1. open': '332.5300',
   '2. high': '335.4800',
   '3. low': '330.7000',
   '4. close': '332.4100',
   '5. volume': '35981000'},
  '2026-09-15': {'1. open': '330.1350',
   '2. high': '331.7800',
   '3. low': '328.3500',
   '4. close': '331.3400',
   '5. volume': '31748183'},
  '2026-09-14': {'1. open': '334.7900',
   '2. high': '335.5000',
   '3. low': '331.3400',
   '4. close': '333.0800',
   '5. volume': '39269147'},
  '2026-09-11': {'1. open': '327.4500',
   '2. high': '336.2200',
   '3. low': '326.3000',
   '4. close': '332.2700',
   '5. volume': '50716865'},
  '2026-09-10': {'1. open': '316.6700',
   '2. high': '326.7400',
   '3. low': '316.5100',
   '4. close': '326.5700',
   '5. volume': '70011913'},
  '2026-09-09': {'1. open': '315.4850',
   '2. high': '319.1500',
   '3. low': '309.9000',
   '4. close': '315.3400',
   '5. volume': '65639962'},
  '2026-09-08': {'1. open': '317.1000',
   '2. high': '320.7000',
   '3. low': '314.9000',
   '4. close': '316.2200',
   '5. volume': '35477090'},
  '2026-09-04': {'1. open': '328.3050',
   '2. high': '328.9300',
   '3. low': '317.8600',
   '4. close': '319.9700',
   '5. volume': '39606884'},
  '2026-09-03': {'1. open': '324.8700',
   '2. high': '330.8100',
   '3. low': '324.1100',
   '4. close': '328.2100',
   '5. volume': '37225838'},
  '2026-09-02': {'1. open': '326.8650',
   '2. high': '328.4000',
   '3. low': '323.5300',
   '4. close': '324.9600',
   '5. volume': '33776370'},
  '2026-09-01': {'1. open': '316.9800',
   '2. high': '327.3000',
   '3. low': '314.7300',
   '4. close': '325.1300',
   '5. volume': '53167388'},
  '2026-08-31': {'1. open': '319.6000',
   '2. high': '321.2350',
   '3. low': '312.8000',
   '4. close': '316.8500',
   '5. volume': '41242724'},
  '2026-08-28': {'1. open': '316.8450',
   '2. high': '322.3700',
   '3. low': '315.4504',
   '4. close': '319.7000',
   '5. volume': '38649398'},
  '2026-08-27': {'1. open': '310.5450',
   '2. high': '315.4000',
   '3. low': '309.4001',
   '4. close': '314.5800',
   '5. volume': '32419233'},
  '2026-08-26': {'1. open': '310.3000',
   '2. high': '315.4300',
   '3. low': '308.8001',
   '4. close': '313.4500',
   '5. volume': '34024486'},
  '2026-08-25': {'1. open': '310.7900',
   '2. high': '313.5900',
   '3. low': '308.2100',
   '4. close': '309.9000',
   '5. volume': '25869807'},
  '2026-08-24': {'1. open': '311.4700',
   '2. high': '313.3600',
   '3. low': '309.9700',
   '4. close': '310.3400',
   '5. volume': '34673582'},
  '2026-08-21': {'1. open': '312.0500',
   '2. high': '312.3800',
   '3. low': '307.0100',
   '4. close': '309.3500',
   '5. volume': '46876815'},
  '2026-08-20': {'1. open': '317.4550',
   '2. high': '320.2800',
   '3. low': '310.6500',
   '4. close': '311.3000',
   '5. volume': '40959184'},
  '2026-08-19': {'1. open': '310.1400',
   '2. high': '319.2799',
   '3. low': '309.6000',
   '4. close': '316.8300',
   '5. volume': '50505646'},
  '2026-08-18': {'1. open': '307.5800',
   '2. high': '311.4900',
   '3. low': '305.7400',
   '4. close': '310.0300',
   '5. volume': '53424535'},
  '2026-08-17': {'1. open': '306.2100',
   '2. high': '307.6600',
   '3. low': '302.9390',
   '4. close': '305.5900',
   '5. volume': '38169263'},
  '2026-08-14': {'1. open': '306.0000',
   '2. high': '307.4900',
   '3. low': '304.3000',
   '4. close': '305.9300',
   '5. volume': '28229375'},
  '2026-08-13': {'1. open': '304.2100',
   '2. high': '306.0000',
   '3. low': '302.0500',
   '4. close': '305.2600',
   '5. volume': '40349289'},
  '2026-08-12': {'1. open': '305.1000',
   '2. high': '305.6600',
   '3. low': '300.5700',
   '4. close': '302.2500',
   '5. volume': '41657768'},
  '2026-08-11': {'1. open': '307.7500',
   '2. high': '309.9700',
   '3. low': '302.7900',
   '4. close': '304.9100',
   '5. volume': '37476746'},
  '2026-08-10': {'1. open': '306.8300',
   '2. high': '308.2600',
   '3. low': '304.6100',
   '4. close': '308.2600',
   '5. volume': '44812503'},
  '2026-08-07': {'1. open': '311.4500',
   '2. high': '314.8100',
   '3. low': '310.7400',
   '4. close': '313.3300',
   '5. volume': '34437191'},
  '2026-08-06': {'1. open': '314.3400',
   '2. high': '316.2894',
   '3. low': '309.2300',
   '4. close': '312.4100',
   '5. volume': '46139901'},
  '2026-08-05': {'1. open': '309.3600',
   '2. high': '311.7100',
   '3. low': '305.6700',
   '4. close': '311.0000',
   '5. volume': '49438763'},
  '2026-08-04': {'1. open': '302.7250',
   '2. high': '310.4200',
   '3. low': '301.3200',
   '4. close': '309.3800',
   '5. volume': '68000969'},
  '2026-08-03': {'1. open': '309.5800',
   '2. high': '311.8000',
   '3. low': '302.5600',
   '4. close': '303.4200',
   '5. volume': '75051951'},
  '2026-07-31': {'1. open': '304.8100',
   '2. high': '310.6900',
   '3. low': '300.0000',
   '4. close': '308.9100',
   '5. volume': '132489137'},
  '2026-07-30': {'1. open': '333.1000',
   '2. high': '334.7500',
   '3. low': '329.5900',
   '4. close': '333.4300',
   '5. volume': '74817792'},
  '2026-07-29': {'1. open': '339.7300',
   '2. high': '344.5699',
   '3. low': '337.3501',
   '4. close': '338.1900',
   '5. volume': '56090840'},
  '2026-07-28': {'1. open': '340.0300',
   '2. high': '342.8900',
   '3. low': '335.6000',
   '4. close': '340.0800',
   '5. volume': '51859042'},
  '2026-07-27': {'1. open': '334.5400',
   '2. high': '339.5700',
   '3. low': '334.0200',
   '4. close': '336.9100',
   '5. volume': '49604297'},
  '2026-07-24': {'1. open': '321.7900',
   '2. high': '334.3700',
   '3. low': '321.6200',
   '4. close': '333.0200',
   '5. volume': '47489415'},
  '2026-07-23': {'1. open': '321.7300',
   '2. high': '323.3000',
   '3. low': '319.3500',
   '4. close': '321.6600',
   '5. volume': '40840778'},
  '2026-07-22': {'1. open': '327.8700',
   '2. high': '328.9995',
   '3. low': '323.3400',
   '4. close': '325.8900',
   '5. volume': '38755929'},
  '2026-07-21': {'1. open': '323.1300',
   '2. high': '329.6000',
   '3. low': '322.2204',
   '4. close': '327.7400',
   '5. volume': '41338917'},
  '2026-07-20': {'1. open': '333.5050',
   '2. high': '333.7100',
   '3. low': '323.6800',
   '4. close': '326.5900',
   '5. volume': '53468008'},
  '2026-07-17': {'1. open': '331.9800',
   '2. high': '334.9900',
   '3. low': '329.0006',
   '4. close': '333.7400',
   '5. volume': '63407059'},
  '2026-07-16': {'1. open': '328.0050',
   '2. high': '334.6800',
   '3. low': '326.7900',
   '4. close': '333.2600',
   '5. volume': '62970617'},
  '2026-07-15': {'1. open': '317.6150',
   '2. high': '328.7300',
   '3. low': '317.3200',
   '4. close': '327.5000',
   '5. volume': '60957644'},
  '2026-07-14': {'1. open': '313.7600',
   '2. high': '316.1900',
   '3. low': '311.9100',
   '4. close': '314.8600',
   '5. volume': '36336829'},
  '2026-07-13': {'1. open': '317.0150',
   '2. high': '323.4500',
   '3. low': '315.7800',
   '4. close': '317.3100',
   '5. volume': '43257804'},
  '2026-07-10': {'1. open': '314.7200',
   '2. high': '316.9100',
   '3. low': '312.1700',
   '4. close': '315.3200',
   '5. volume': '34132321'},
  '2026-07-09': {'1. open': '310.5100',
   '2. high': '316.5300',
   '3. low': '308.1600',
   '4. close': '316.2200',
   '5. volume': '48124490'},
  '2026-07-08': {'1. open': '311.9100',
   '2. high': '314.8200',
   '3. low': '307.0500',
   '4. close': '313.3900',
   '5. volume': '41323480'},
  '2026-07-07': {'1. open': '315.2900',
   '2. high': '315.4800',
   '3. low': '310.1500',
   '4. close': '310.6600',
   '5. volume': '42490002'},
  '2026-07-06': {'1. open': '307.3600',
   '2. high': '314.2000',
   '3. low': '307.0000',
   '4. close': '312.6600',
   '5. volume': '53589977'},
  '2026-07-02': {'1. open': '294.1200',
   '2. high': '309.4200',
   '3. low': '293.6800',
   '4. close': '308.6300',
   '5. volume': '75400626'},
  '2026-07-01': {'1. open': '293.4400',
   '2. high': '296.5900',
   '3. low': '289.1950',
   '4. close': '294.3800',
   '5. volume': '50164232'},
  '2026-06-30': {'1. open': '281.1700',
   '2. high': '289.9400',
   '3. low': '280.6950',
   '4. close': '289.3600',
   '5. volume': '65100155'},
  '2026-06-29': {'1. open': '286.7300',
   '2. high': '288.3697',
   '3. low': '279.8500',
   '4. close': '281.7400',
   '5. volume': '66427002'},
  '2026-06-26': {'1. open': '275.0000',
   '2. high': '285.9500',
   '3. low': '274.2100',
   '4. close': '283.7800',
   '5. volume': '261775450'},
  '2026-06-25': {'1. open': '287.4000',
   '2. high': '288.8000',
   '3. low': '273.7500',
   '4. close': '275.1500',
   '5. volume': '107253659'},
  '2026-06-24': {'1. open': '295.3550',
   '2. high': '299.7000',
   '3. low': '292.9400',
   '4. close': '293.0800',
   '5. volume': '53081859'},
  '2026-06-23': {'1. open': '297.5380',
   '2. high': '301.6400',
   '3. low': '294.1800',
   '4. close': '294.3000',
   '5. volume': '52010929'},
  '2026-06-22': {'1. open': '297.3100',
   '2. high': '302.4200',
   '3. low': '296.7600',
   '4. close': '297.0100',
   '5. volume': '44879914'},
  '2026-06-18': {'1. open': '298.1100',
   '2. high': '300.5700',
   '3. low': '295.6200',
   '4. close': '298.0100',
   '5. volume': '85962201'},
  '2026-06-17': {'1. open': '300.8450',
   '2. high': '302.0700',
   '3. low': '294.3600',
   '4. close': '295.9500',
   '5. volume': '42745060'},
  '2026-06-16': {'1. open': '295.2450',
   '2. high': '300.4800',
   '3. low': '293.9700',
   '4. close': '299.2400',
   '5. volume': '39874404'},
  '2026-06-15': {'1. open': '294.1200',
   '2. high': '297.7800',
   '3. low': '291.7000',
   '4. close': '296.4200',
   '5. volume': '45732573'},
  '2026-06-12': {'1. open': '296.0300',
   '2. high': '297.1400',
   '3. low': '289.6200',
   '4. close': '291.1300',
   '5. volume': '38784789'},
  '2026-06-11': {'1. open': '293.7200',
   '2. high': '297.0000',
   '3. low': '289.5900',
   '4. close': '295.6300',
   '5. volume': '42572497'},
  '2026-06-10': {'1. open': '290.7400',
   '2. high': '294.7500',
   '3. low': '287.3800',
   '4. close': '291.5800',
   '5. volume': '52793266'},
  '2026-06-09': {'1. open': '300.2750',
   '2. high': '300.7500',
   '3. low': '287.7800',
   '4. close': '290.5500',
   '5. volume': '70108847'},
  '2026-06-08': {'1. open': '308.7390',
   '2. high': '317.4000',
   '3. low': '301.1700',
   '4. close': '301.5400',
   '5. volume': '77949082'},
  '2026-06-05': {'1. open': '312.8600',
   '2. high': '315.1700',
   '3. low': '307.1500',
   '4. close': '307.3400',
   '5. volume': '65310502'},
  '2026-06-04': {'1. open': '313.2300',
   '2. high': '313.5400',
   '3. low': '309.6500',
   '4. close': '311.2300',
   '5. volume': '44869134'},
  '2026-06-03': {'1. open': '314.1750',
   '2. high': '316.9400',
   '3. low': '308.8500',
   '4. close': '310.2600',
   '5. volume': '50836705'},
  '2026-06-02': {'1. open': '307.4600',
   '2. high': '315.4500',
   '3. low': '306.6850',
   '4. close': '315.2000',
   '5. volume': '44534716'},
  '2026-06-01': {'1. open': '309.6250',
   '2. high': '310.9400',
   '3. low': '305.0200',
   '4. close': '306.3100',
   '5. volume': '48849933'},
  '2026-05-29': {'1. open': '311.7750',
   '2. high': '315.0000',
   '3. low': '309.5300',
   '4. close': '312.0600',
   '5. volume': '70026752'},
  '2026-05-28': {'1. open': '310.6800',
   '2. high': '312.8000',
   '3. low': '309.5700',
   '4. close': '312.5100',
   '5. volume': '48220390'},
  '2026-05-27': {'1. open': '308.3300',
   '2. high': '313.2600',
   '3. low': '308.3000',
   '4. close': '310.8500',
   '5. volume': '50430919'},
  '2026-05-26': {'1. open': '309.5600',
   '2. high': '311.8200',
   '3. low': '307.6700',
   '4. close': '308.3300',
   '5. volume': '48000493'},
  '2026-05-22': {'1. open': '306.1200',
   '2. high': '311.4000',
   '3. low': '305.8400',
   '4. close': '308.8200',
   '5. volume': '43670223'},
  '2026-05-21': {'1. open': '301.0550',
   '2. high': '305.5400',
   '3. low': '300.4000',
   '4. close': '304.9900',
   '5. volume': '42965126'},
  '2026-05-20': {'1. open': '298.1800',
   '2. high': '302.8000',
   '3. low': '298.0800',
   '4. close': '302.2500',
   '5. volume': '37307876'}}}

In [16]:
meta_data = data['Meta Data']
meta_df = pd.DataFrame.from_dict(meta_data, orient='index')
meta_df

                                                                   0
1. Information     Daily Prices (open, high, low, close) and Volumes
2. Symbol                                                       AAPL
3. Last Refreshed                                         2026-10-12
4. Output Size                                               Compact
5. Time Zone                                              US/Eastern

In [11]:
daily = data["Time Series (Daily)"]

df = (
    pd.DataFrame.from_dict(daily, orient="index")
    .rename(
        columns={
            "1. open": "open",
            "2. high": "high",
            "3. low": "low",
            "4. close": "close",
            "5. volume": "volume",
        }
    )
    .rename_axis("date")
    .reset_index()
)

df["date"] = pd.to_datetime(df["date"])

for col in ["open", "high", "low", "close"]:
    df[col] = pd.to_numeric(df[col])

df["volume"] = pd.to_numeric(df["volume"])

df

         date     open    high     low   close    volume
0  2026-10-12  338.215  342.63  337.60  340.97  25900599
1  2026-10-09  331.695  338.61  330.70  336.64  37881199
2  2026-10-08  336.815  341.57  335.90  340.42  35332449
3  2026-10-07  336.960  338.67  332.78  336.67  34147860
4  2026-10-06  332.280  334.38  330.62  333.63  30449005
..        ...      ...     ...     ...     ...       ...
95 2026-05-27  308.330  313.26  308.30  310.85  50430919
96 2026-05-26  309.560  311.82  307.67  308.33  48000493
97 2026-05-22  306.120  311.40  305.84  308.82  43670223
98 2026-05-21  301.055  305.54  300.40  304.99  42965126
99 2026-05-20  298.180  302.80  298.08  302.25  37307876

[100 rows x 6 columns]

In [6]:
def get_daily_stock_price(company, start_date, end_date):
    API_TOKEN = os.getenv('TIINGO_API_TOKEN')

    ticker = company
    start_date = start_date
    end_date = end_date

    url = f"https://api.tiingo.com/tiingo/daily/{ticker}/prices"

    params = {
        "startDate": start_date,
        "endDate": end_date,
        "token": API_TOKEN,
    }

    response = requests.get(url, params=params)
    response.raise_for_status()

    data = response.json()

    df = pd.DataFrame(data)
    raw_df = df[
        [
            "date",
            "open",
            "high",
            "low",
            "close",
            "volume",
        ]
    ].copy()

    raw_df["date"] = pd.to_datetime(raw_df["date"]).dt.date

    for col in ["open", "high", "low", "close"]:
        raw_df[col] = pd.to_numeric(raw_df[col])

    raw_df["volume"] = pd.to_numeric(raw_df["volume"])
    
    
    return raw_df

In [7]:
apple = get_daily_stock_price(
    company="AAPL",
    start_date = "2025-10-01",
    end_date = "2025-10-01"
    )
apple

         date    open    high     low   close    volume
0  2025-10-01  255.04  258.79  254.93  255.45  48713940